#!/bin/bash
# Download all LFS 12.2 package sources
set -e
cd /lfs/usr/src

# Define packages with URLs and expected tarball names
# Format: "name version url filename"
declare -A PKGS
PKGS=(
    ["acl"]="https://download.savannah.gnu.org/releases/acl/acl-2.3.2.tar.xz"
    ["attr"]="https://download.savannah.gnu.org/releases/attr/attr-2.5.2.tar.gz"
    ["autoconf"]="https://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.xz"
    ["automake"]="https://ftp.gnu.org/gnu/automake/automake-1.17.tar.xz"
    ["bash"]="https://ftp.gnu.org/gnu/bash/bash-5.2.32.tar.gz"
    ["bc"]="https://github.com/gavinhoward/bc/releases/download/6.7.6/bc-6.7.6.tar.xz"
    ["binutils"]="https://ftp.gnu.org/gnu/binutils/binutils-2.43.1.tar.xz"
    ["bison"]="https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.xz"
    ["bzip2"]="https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"
    ["check"]="https://github.com/libcheck/check/releases/download/0.15.2/check-0.15.2.tar.gz"
    ["coreutils"]="https://ftp.gnu.org/gnu/coreutils/coreutils-9.5.tar.xz"
    ["dejagnu"]="https://ftp.gnu.org/gnu/dejagnu/dejagnu-1.6.3.tar.gz"
    ["diffutils"]="https://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz"
    ["e2fsprogs"]="https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v1.47.1/e2fsprogs-1.47.1.tar.gz"
    ["expat"]="https://github.com/libexpat/libexpat/releases/download/R_2_6_2/expat-2.6.2.tar.xz"
    ["expect"]="https://downloads.sourceforge.net/tcl/expect5.45.4.tar.gz"
    ["file"]="https://astron.com/pub/file/file-5.45.tar.gz"
    ["findutils"]="https://ftp.gnu.org/gnu/findutils/findutils-4.10.0.tar.xz"
    ["flex"]="https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz"
    ["gawk"]="https://ftp.gnu.org/gnu/gawk/gawk-5.3.0.tar.xz"
    ["gcc"]="https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.xz"
    ["gdbm"]="https://ftp.gnu.org/gnu/gdbm/gdbm-1.24.tar.gz"
    ["gettext"]="https://ftp.gnu.org/gnu/gettext/gettext-0.22.5.tar.xz"
    ["glibc"]="https://ftp.gnu.org/gnu/glibc/glibc-2.40.tar.xz"
    ["gmp"]="https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz"
    ["gperf"]="https://ftp.gnu.org/gnu/gperf/gperf-3.1.tar.gz"
    ["grep"]="https://ftp.gnu.org/gnu/grep/grep-3.11.tar.xz"
    ["groff"]="https://ftp.gnu.org/gnu/groff/groff-1.23.0.tar.gz"
    ["grub"]="https://ftp.gnu.org/gnu/grub/grub-2.12.tar.xz"
    ["gzip"]="https://ftp.gnu.org/gnu/gzip/gzip-1.13.tar.xz"
    ["inetutils"]="https://ftp.gnu.org/gnu/inetutils/inetutils-2.5.tar.xz"
    ["intltool"]="https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-0.51.0.tar.gz"
    ["iproute2"]="https://www.kernel.org/pub/linux/utils/net/iproute2/iproute2-6.10.0.tar.xz"
    ["kbd"]="https://www.kernel.org/pub/linux/utils/kbd/kbd-2.6.4.tar.xz"
    ["kmod"]="https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-32.tar.xz"
    ["less"]="https://www.greenwoodsoftware.com/less/less-661.tar.gz"
    ["libcap"]="https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.70.tar.xz"
    ["libelf"]="https://sourceware.org/ftp/elfutils/0.191/elfutils-0.191.tar.bz2"
    ["libffi"]="https://github.com/libffi/libffi/releases/download/v3.4.6/libffi-3.4.6.tar.gz"
    ["libpipeline"]="https://download.savannah.gnu.org/releases/libpipeline/libpipeline-1.5.7.tar.gz"
    ["libtool"]="https://ftp.gnu.org/gnu/libtool/libtool-2.4.7.tar.xz"
    ["libxcrypt"]="https://github.com/besser82/libxcrypt/releases/download/v4.4.36/libxcrypt-4.4.36.tar.xz"
    ["linux"]="https://www.kernel.org/pub/linux/kernel/v6.x/linux-6.10.5.tar.xz"
    ["lz4"]="https://github.com/lz4/lz4/releases/download/v1.9.4/lz4-1.9.4.tar.gz"
    ["m4"]="https://ftp.gnu.org/gnu/m4/m4-1.4.19.tar.xz"
    ["make"]="https://ftp.gnu.org/gnu/make/make-4.4.1.tar.gz"
    ["man-db"]="https://download.savannah.gnu.org/releases/man-db/man-db-2.12.1.tar.xz"
    ["man-pages"]="https://www.kernel.org/pub/linux/docs/man-pages/man-pages-6.06.tar.xz"
    ["meson"]="https://github.com/mesonbuild/meson/releases/download/1.5.1/meson-1.5.1.tar.gz"
    ["mpc"]="https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz"
    ["mpfr"]="https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.1.tar.xz"
    ["ncurses"]="https://ftp.gnu.org/gnu/ncurses/ncurses-6.5.tar.gz"
    ["ninja"]="https://github.com/ninja-build/ninja/archive/v1.12.1/ninja-1.12.1.tar.gz"
    ["openssl"]="https://www.openssl.org/source/openssl-3.3.1.tar.gz"
    ["patch"]="https://ftp.gnu.org/gnu/patch/patch-2.7.6.tar.xz"
    ["perl"]="https://www.cpan.org/src/5.0/perl-5.40.0.tar.xz"
    ["pkgconf"]="https://distfiles.ariadne.space/pkgconf/pkgconf-2.2.0.tar.xz"
    ["procps-ng"]="https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-4.0.4.tar.xz"
    ["psmisc"]="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-23.7.tar.xz"
    ["python"]="https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tar.xz"
    ["readline"]="https://ftp.gnu.org/gnu/readline/readline-8.2.13.tar.gz"
    ["sed"]="https://ftp.gnu.org/gnu/sed/sed-4.9.tar.xz"
    ["shadow"]="https://github.com/shadow-maint/shadow/releases/download/4.16.0/shadow-4.16.0.tar.gz"
    ["sysklogd"]="https://github.com/troglobit/sysklogd/releases/download/v2.5.2/sysklogd-2.5.2.tar.gz"
    ["sysvinit"]="https://github.com/slicer69/sysvinit/releases/download/3.09/sysvinit-3.09.tar.xz"
    ["tar"]="https://ftp.gnu.org/gnu/tar/tar-1.35.tar.xz"
    ["tcl"]="https://downloads.sourceforge.net/tcl/tcl8.6.14-src.tar.gz"
    ["texinfo"]="https://ftp.gnu.org/gnu/texinfo/texinfo-7.1.tar.xz"
    ["util-linux"]="https://www.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.2.tar.xz"
    ["vim"]="https://github.com/vim/vim/archive/v9.1.0678/vim-9.1.0678.tar.gz"
    ["xml-parser"]="https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.47.tar.gz"
    ["xz"]="https://github.com/tukaani-project/xz/releases/download/v5.6.2/xz-5.6.2.tar.xz"
    ["zlib"]="https://zlib.net/fossils/zlib-1.3.1.tar.gz"
    ["zstd"]="https://github.com/facebook/zstd/releases/download/v1.5.6/zstd-1.5.6.tar.gz"
    ["iana-etc"]="https://github.com/Mic92/iana-etc/releases/download/20240814/iana-etc-20240814.tar.gz"
)

for pkg in "${!PKGS[@]}"; do
    url="${PKGS[$pkg]}"
    fname=$(basename "$url")
    if [ ! -f "$fname" ]; then
        echo "Downloading $pkg: $fname"
        wget -q "$url" || echo "WARN: failed to download $pkg from $url"
    else
        echo "Already have $fname"
    fi
done

echo "Downloads complete."
ls -la /lfs/usr/src/ | wc -l
echo "files in src dir"
