#!/usr/bin/env bash
#
# Interactive terminal configuration for shitix (whiptail/dialog TUI).
# Mirrors the Linux kernel's `make menuconfig` workflow, editing `.config`.
#
# Run via `make menuconfig` or directly: bash scripts/menuconfig.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DEFAULTS="config/defaults"
CONFIG_FILE=".config"
TITLE="shitix kernel configuration"

# ---- load values: defaults first, then .config (overrides) ----------------
declare -A CFG
load() {
    local f line k v
    for f in "$DEFAULTS" "$CONFIG_FILE"; do
        [[ -f "$f" ]] || continue
        while IFS='=' read -r k v; do
            [[ -z "$k" ]] && continue
            k="${k//[[:space:]]/}"
            v="${v//[[:space:]]/}"
            CFG["$k"]="$v"
        done < <(grep -vE '^\s*(#|$)' "$f")
    done
}
load

# Defaults in case a key is absent
CFG[CONFIG_PROFILE]="${CFG[CONFIG_PROFILE]:-debug}"
CFG[CONFIG_EXTRA_DRIVERS]="${CFG[CONFIG_EXTRA_DRIVERS]:-n}"
CFG[CONFIG_MEM]="${CFG[CONFIG_MEM]:-256M}"
CFG[CONFIG_TIMEOUT]="${CFG[CONFIG_TIMEOUT]:-20}"
CFG[CONFIG_ROOTIMG]="${CFG[CONFIG_ROOTIMG]:-}"
CFG[CONFIG_VERSION]="${CFG[CONFIG_VERSION]:-0.1.0}"
CFG[CONFIG_INSTALL_ROOT]="${CFG[CONFIG_INSTALL_ROOT]:-}"
CFG[CONFIG_INSTALL_BOOTDIR]="${CFG[CONFIG_INSTALL_BOOTDIR]:-/boot}"

# ---- small display helpers -------------------------------------------------
disp() { # $1 = raw value, $2 = fallback text when empty
    local v="$1"
    [[ -n "$v" ]] || v="$2"
    printf '%s' "$v"
}

# ---- per-option editors ----------------------------------------------------
edit_bool() { # $1 key, $2 label
    local cur="${CFG[$1]}" def=0
    [[ "$cur" == "y" ]] && def=1
    if whiptail --title "$TITLE" --yesno "$2" 0 0 "$def" 3>&1 1>&2 2>&3; then
        CFG[$1]=y
    else
        CFG[$1]=n
    fi
}

edit_choice() { # $1 key, $2 label; choices: $3, $4
    local cur="${CFG[$1]}" a="$3" b="$4" res
    res="$(whiptail --title "$TITLE" --menu "$2" 0 0 2 \
        "$a" "$a" "$b" "$b" 3>&1 1>&2 2>&3)" || return
    CFG[$1]="$res"
}

edit_string() { # $1 key, $2 label
    local cur="${CFG[$1]}" res
    res="$(whiptail --title "$TITLE" --inputbox "$2" 0 0 "$cur" 3>&1 1>&2 2>&3)" || return
    CFG[$1]="$res"
}

# ---- save ------------------------------------------------------------------
save() {
    {
        printf '# shitix kernel configuration\n'
        printf '#   Generated by scripts/menuconfig.sh (terminal).\n'
        printf '#   Edit with: make config | make menuconfig   Reset: make defconfig\n\n'
        printf '# Build profile: debug | release\nCONFIG_PROFILE=%s\n\n' "${CFG[CONFIG_PROFILE]}"
        printf '# Extra drivers (IDE/ATA): y | n\nCONFIG_EXTRA_DRIVERS=%s\n\n' "${CFG[CONFIG_EXTRA_DRIVERS]}"
        printf '# QEMU memory size\nCONFIG_MEM=%s\n\n' "${CFG[CONFIG_MEM]}"
        printf '# Test timeout (seconds)\nCONFIG_TIMEOUT=%s\n\n' "${CFG[CONFIG_TIMEOUT]}"
        printf '# Optional root image (2nd IDE drive); empty = none\nCONFIG_ROOTIMG=%s\n\n' "${CFG[CONFIG_ROOTIMG]}"
        printf '# Kernel version\nCONFIG_VERSION=%s\n\n' "${CFG[CONFIG_VERSION]}"
        printf '# Install prefix; empty = auto\nCONFIG_INSTALL_ROOT=%s\n\n' "${CFG[CONFIG_INSTALL_ROOT]}"
        printf '# Boot directory\nCONFIG_INSTALL_BOOTDIR=%s\n' "${CFG[CONFIG_INSTALL_BOOTDIR]}"
    } > "$CONFIG_FILE"
}

# ---- main menu loop --------------------------------------------------------
while true; do
    choice="$(whiptail --title "$TITLE" \
        --menu "Select an option to change, or save and exit." 0 0 0 \
        profile      "Build profile           [$(disp "${CFG[CONFIG_PROFILE]}" '')]" \
        drivers      "Extra drivers (IDE)    [$(disp "${CFG[CONFIG_EXTRA_DRIVERS]}" '')]" \
        mem          "QEMU memory            [$(disp "${CFG[CONFIG_MEM]}" '')]" \
        timeout      "Test timeout (s)       [$(disp "${CFG[CONFIG_TIMEOUT]}" '')]" \
        rootimg      "Root filesystem image  [$(disp "${CFG[CONFIG_ROOTIMG]}" '<none>')]" \
        version      "Kernel version         [$(disp "${CFG[CONFIG_VERSION]}" '')]" \
        install_root "Install root (LFS)     [$(disp "${CFG[CONFIG_INSTALL_ROOT]}" '<auto>')]" \
        bootdir      "Boot directory         [$(disp "${CFG[CONFIG_INSTALL_BOOTDIR]}" '')]" \
        save         "Save and exit" \
        3>&1 1>&2 2>&3)" || {
        # user cancelled (Esc) — exit without saving
        echo "  cancelled (no changes saved)"
        exit 0
    }

    case "$choice" in
        profile)
            edit_choice CONFIG_PROFILE "Build profile" debug release
            ;;
        drivers)
            edit_bool CONFIG_EXTRA_DRIVERS "Enable extra drivers (IDE/ATA)?"
            ;;
        mem)
            edit_string CONFIG_MEM "QEMU memory size (e.g. 256M):"
            ;;
        timeout)
            edit_string CONFIG_TIMEOUT "Headless test timeout in seconds:"
            ;;
        rootimg)
            edit_string CONFIG_ROOTIMG "Root filesystem image path (empty = none):"
            ;;
        version)
            edit_string CONFIG_VERSION "Kernel version string:"
            ;;
        install_root)
            edit_string CONFIG_INSTALL_ROOT "Install root prefix (empty = auto-detect):"
            ;;
        bootdir)
            edit_string CONFIG_INSTALL_BOOTDIR "Boot directory (e.g. /boot):"
            ;;
        save)
            save
            echo "  wrote .config"
            exit 0
            ;;
    esac
done
